version: '3.8'

services:
  viewer:
    build: .
    container_name: obsidian-viewer-app
    ports:
      - "8000:8000"
    volumes:
      - ./content:/app/content
      - ./static:/app/static
      - ./templates:/app/templates
      - ./main.py:/app/main.py
      # 外部のObsidian保管庫などをアプリ内から参照したい場合は、ここに追加マウントを記述します。
      # 例 (Windows): - D:\Documents\Obsidian:/0_host_pc:ro
      # 設定したら、ブラウザ上で /0_host_pc を参照してください。
      - D:\Obsidian\Obisidian-Vault\Obsidian-DB:/0_host_pc:ro
    restart: always
